### ISSUE TITLE
Can't export OPML

### ISSUE THREAD

**Issue by ghost** [hardware/selfoss#10]
```
[2018-05-21 21:45:57] selfoss.ERROR: Class 'XMLWriter' not found {"exception":"[object] (Error(code: 0): Class 'XMLWriter' not found at /selfoss/controllers/Opml.php:273)
[stacktrace]
#0 /selfoss/vendor/bcosca/fatfree-core/base.php(1806): controllers\\Opml->export(Object(Base), Array, 'controllers\\\\Opm...')
#1 /selfoss/vendor/bcosca/fatfree-core/base.php(1627): Base->call(Array, Array, Array)
#2 /selfoss/index.php(80): Base->run()
#3 {main}
"} 
```

'php7-xml' and 'php7-xmlwriter' packages missing

**Comment by hardware** [comment]
Sorry for the delay. This issue should be fixed now.
